[project]
requires-python = ">=3.10"

[tool.ruff]
exclude = [
]
line-length = 120

[tool.ruff.lint]
ignore-init-module-imports = true
select = [
    "B", # flake8-bugbear rules
    "F", # pyflakes rules
    "I", # isort rules
    "UP",   # pyupgrade rules
    "RUF019", # unnecessary-key-check
    "S506", # unsafe-yaml-load
    "W605", # invalid-escape-sequence
]
ignore = [
    "F403", # undefined-local-with-import-star
    "F405", # undefined-local-with-import-star-usage
    "F821", # undefined-name
    "F841", # unused-variable
    "UP007", # non-pep604-annotation
    "UP032", # f-string
    "B005", # strip-with-multi-characters
    "B006", # mutable-argument-default
    "B007", # unused-loop-control-variable
    "B026", # star-arg-unpacking-after-keyword-arg
    "B904", # raise-without-from-inside-except
    "B905", # zip-without-explicit-strict
]

[tool.ruff.lint.per-file-ignores]
"app.py" = [
    "F401", # unused-import
    "F811", # redefined-while-unused
]
"__init__.py" = [
    "F401", # unused-import
    "F811", # redefined-while-unused
]
"tests/*" = [
    "F401", # unused-import
    "F811", # redefined-while-unused
]


[tool.pytest_env]
MOCK_SWITCH = "true"
CODE_MAX_STRING_LENGTH = "80000"
CODE_EXECUTION_ENDPOINT="http://127.0.0.1:8194"
CODE_EXECUTION_API_KEY="dify-sandbox"

[tool.poetry]
name = "dify"
version = "0.1.0"
description = ""
authors = ["shawn <wangshiyang@aliyun.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
beautifulsoup4 = "4.12.2"
flask = ">=3.0.1,<3.1.0"
flask-sqlalchemy = ">=3.0.5,<3.1.0"
sqlalchemy = ">=2.0.29,<2.1.0"
flask-compress = ">=1.14,<2.0"
flask-login = ">=0.6.3,<0.7.0"
flask-migrate = ">=4.0.5,<4.1.0"
flask-restful = ">=0.3.10,<0.4.0"
flask-cors = ">=4.0.0,<4.1.0"
gunicorn = ">=22.0.0,<22.1.0"
gevent = ">=23.9.1,<23.10.0"
openai = ">=1.29.0,<1.30.0"
tiktoken = ">=0.7.0,<0.8.0"
psycopg2-binary = ">=2.9.6,<2.10.0"
pycryptodome = "3.19.1"
python-dotenv = "1.0.0"
authlib = "1.2.0"
boto3 = "1.28.17"
tenacity = "8.2.2"
cachetools = ">=5.3.0,<5.4.0"
weaviate-client = ">=3.21.0,<3.22.0"
mailchimp-transactional = ">=1.0.50,<1.1.0"
scikit-learn = "1.2.2"
sentry-sdk = {version = ">=1.39.2,<1.40.0", extras = ["flask"]}
sympy = "1.12"
jieba = "0.42.1"
celery = ">=5.3.6,<5.4.0"
redis = {version = ">=5.0.3,<5.1.0", extras = ["hiredis"]}
openpyxl = "3.1.2"
chardet = ">=5.1.0,<5.2.0"
python-docx = ">=1.1.0,<1.2.0"
pypdfium2 = ">=4.17.0,<4.18.0"
resend = ">=0.7.0,<0.8.0"
pyjwt = ">=2.8.0,<2.9.0"
anthropic = ">=0.23.1,<0.24.0"
newspaper3k = "0.2.8"
wikipedia = "1.4.0"
readabilipy = "0.2.0"
google-ai-generativelanguage = "0.6.1"
google-api-core = "2.18.0"
google-api-python-client = "2.90.0"
google-auth = "2.29.0"
google-auth-httplib2 = "0.2.0"
google-generativeai = "0.5.0"
google-search-results = "2.4.2"
googleapis-common-protos = "1.63.0"
google-cloud-storage = "2.16.0"
replicate = ">=0.22.0,<0.23.0"
websocket-client = ">=1.7.0,<1.8.0"
dashscope = {version = ">=1.17.0,<1.18.0", extras = ["tokenizer"]}
huggingface-hub = ">=0.16.4,<0.17.0"
transformers = ">=4.35.0,<4.36.0"
tokenizers = ">=0.15.0,<0.16.0"
pandas = "1.5.3"
xinference-client = "0.9.4"
safetensors = ">=0.4.3,<0.5.0"
zhipuai = "1.0.7"
werkzeug = ">=3.0.1,<3.1.0"
pymilvus = "2.4.3"
qdrant-client = "1.7.3"
cohere = ">=5.2.4,<5.3.0"
pyyaml = ">=6.0.1,<6.1.0"
numpy = ">=1.26.4,<1.27.0"
unstructured = {version = ">=0.10.27,<0.11.0", extras = ["docx", "epub", "md", "msg", "ppt", "pptx"]}
bs4 = ">=0.0.1,<0.1.0"
markdown = ">=3.5.1,<3.6.0"
httpx = {version = ">=0.24.1,<0.25.0", extras = ["socks"]}
matplotlib = ">=3.8.2,<3.9.0"
yfinance = ">=0.2.40,<0.3.0"
pydub = ">=0.25.1,<0.26.0"
gmpy2 = ">=2.1.5,<2.2.0"
numexpr = ">=2.9.0,<2.10.0"
duckduckgo-search = "5.2.2"
arxiv = "2.1.0"
yarl = ">=1.9.4,<1.10.0"
twilio = ">=9.0.4,<9.1.0"
qrcode = ">=7.4.2,<7.5.0"
azure-storage-blob = "12.13.0"
azure-identity = "1.15.0"
lxml = "5.1.0"
xlrd = ">=2.0.1,<2.1.0"
pydantic = ">=1.10.0,<1.11.0"
pgvecto-rs = "0.1.4"
firecrawl-py = "0.0.5"
oss2 = "2.18.5"
pgvector = "0.2.5"
google-cloud-aiplatform = "1.54.1"
flax = "^0.8.4"
kaleido = "0.2.1"
vanna = {version = "0.5.5", extras = ["clickhouse", "duckdb", "mysql", "postgres"]}
python-postmark-inbound = "^1.1.0"
grpcio = "1.63.0"
